server:
  port: 8080
  servlet:
    context-path: /
spring:
  messages:
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://139.159.162.156:3306/zz?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=UTC
    username: my
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:H:/html/html/
#    prefix: classpath:file:${web.upload.path}
    suffix: .html
  #链接配置
  redis:
    host: 47.94.81.127
    password:
    port: 6379
    jedis:
      pool:
        #连接池最大活动连接
        max-active: 30
        #最大空闲链接
        max-idle: 10
        #超过时间
        max-wait: 10ms
        #连接池最小空闲连接
        min-idle: 3
  cache:
    cache-names: redis-cache
    redis:
      cache-null-values: true #是否可以储存空值
      time-to-live: 300s
      use-key-prefix: true
  jmx:
    enabled: false
  #    设置上传文件大小
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB

#日志配置
#logging:
#  pattern:
#    console: "%d - #msg%n" #控制台输出日志，（时间、消息）

#静态资源文件
web:
  upload:
    path: /zzbmImg/userHead
  resources:
    static-locations: classpath:/static/,file:${web.upload.path}

#微信支付定义的参数
wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
#回调地址
  notify_url: http://gzcstec.com/sell/pay/notify






